# Generated by Django 5.2.7 on 2025-11-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_condition_product_instagram_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, unique=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_days', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_days',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
